# Generated by Django 4.1.7 on 2023-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(default=None, max_length=100)),
                ('Lastname', models.CharField(default=None, max_length=100)),
                ('Number', models.CharField(default=None, max_length=100)),
                ('Email', models.CharField(default=None, max_length=100)),
                ('Username', models.CharField(default=None, max_length=100)),
                ('Password', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
